version: '3.7'

networks:
  app-tier:
    driver: bridge

services:
  L3Matching:
    build:
      context: src
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - app-tier
    volumes:
      - type: bind
        source: ./src
        target: /app

    command: >
      uvicorn main:app --host 0.0.0.0 --port 3001 --reload"

  
  postgres:
    image: postgres:17.0-alpine
    restart: always
    ports:
      - 15432:5432
    networks:
      - app-tier
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./data/pg_history:/var/lib/postgresql/data